services:
  - type: web
    name: ngram-api
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT api.index:app
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG_MODE
        value: false
      - key: GEMINI_API_KEY
        sync: false
